[package]
name = "{DAY}"
version = "0.1.0"
authors = ["Dave Bort <git@dbort.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
