[workspace]
resolver = "3"
members = [
  "2025/day01",
  "2025/day02",
  "2025/day03",
  "2025/day04",
  "2025/day05",
  "2025/day06",
  "2025/day07",
  "2025/day08",
  "2025/day09",
  # <INSERT_MEMBER
]
